ARG version
FROM almalinux:${version:-8}
ARG siddhu="wastfellow"
ARG swathi="sodhi"
ENV swathi=${swathi}
RUN echo "siddhu doing ${siddhu} and swathi is ${swathi} "
CMD ["sleep", "100"]


# How can you check OS of your Server? cat /etc?*release