ARG version
FROM almalinux:${version:-8}
ARG siddhu="wastfellow"
ARG sindhu="sodhi"
ENV swathi="smallgirl"
RUN echo "siddhu doing ${siddhu} sindhus ${sindhu} "
CMD ["sleep", "100"]


# How can you check OS of your Server? cat /etc?*release